### ISSUE TITLE
json files should be "pretty" printed

### ISSUE THREAD

**Issue by osallou** [bio-tools/content#15]
the json compact form will not ease the pull requests reviews.

If a pull request is done to add, for example, a *download* element, the compact form will only show, as **diff**, the full line. It makes it difficult for manual review to see the changes.

With a *pretty print*, we could see the impacted lines.

**Comment by hansioan** [comment]
@osallou 
I am not sure what you mean, the json files are pretty printed. Are they in compact form for you?

**Comment by osallou** [comment]
sorry, was a problem on my side.....
