### ISSUE TITLE
huge pending PRs

### ISSUE THREAD

**Issue by osallou** [bio-tools/content#280]
Hi,
we have **many** pending PRs injected by github-actions , will soon add confusion to handle PRs....

**Comment by hmenager** [comment]
I can remove the PRs, as they were introduced by tests on the CI mechanism.
does anyone need them?

**Comment by hansioan** [comment]
We could probably remove most PRs as the content here is just for testing purposes.

**Comment by hmenager** [comment]
should be almost fine now :)
